-- Purple Boutique catalog foundation
-- Run this migration once in Supabase SQL Editor, then run seed_catalog.sql.

begin;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_ta text not null default '',
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists categories_name_en_lower_unique
  on public.categories ((lower(trim(name_en))));

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  name_ta text not null default '',
  tamil_name text not null default '',
  category text not null default '',
  category_id bigint references public.categories(id) on delete set null,
  remedy jsonb not null default '[]'::jsonb,
  price numeric(12,2) not null default 0 check (price >= 0),
  offer_price numeric(12,2) check (offer_price is null or offer_price >= 0),
  purchase_price numeric(12,2) check (purchase_price is null or purchase_price >= 0),
  mrp numeric(12,2) check (mrp is null or mrp >= 0),
  sku text,
  barcode text,
  unit_type text not null default 'unit',
  unit_label text not null default 'pc',
  base_quantity numeric(12,3) not null default 1,
  stock_quantity numeric(12,3) not null default 0,
  stock integer not null default 0,
  stock_unit text not null default 'pc',
  allow_decimal_quantity boolean not null default false,
  predefined_options jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  unit text not null default '1pc',
  rating numeric(3,2),
  description text not null default '',
  description_ta text not null default '',
  benefits jsonb not null default '[]'::jsonb,
  benefits_ta jsonb not null default '[]'::jsonb,
  image_url text,
  image text,
  has_variants boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_category_id_idx on public.products(category_id);
create index if not exists products_active_sort_idx on public.products(is_active, sort_order, name);
create unique index if not exists products_sku_unique on public.products(sku) where sku is not null and sku <> '';
create unique index if not exists products_barcode_unique on public.products(barcode) where barcode is not null and barcode <> '';

alter table public.categories enable row level security;
alter table public.products enable row level security;

drop policy if exists "Authenticated users can read categories" on public.categories;
drop policy if exists "Public can read active categories" on public.categories;
create policy "Public can read active categories"
  on public.categories for select to anon, authenticated using (is_active = true);

drop policy if exists "Authenticated users can read products" on public.products;
drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
  on public.products for select to anon, authenticated using (is_active = true);

grant usage on schema public to anon, authenticated;
grant select on public.categories, public.products to anon, authenticated;

commit;
